// category list used across the app
const CATEGORIES = [
  "Salary",
  "Freelance",
  "Investment",
  "Food & Dining",
  "Transport",
  "Shopping",
  "Entertainment",
  "Health",
  "Education",
  "Utilities",
];

const catIcons = {
  Salary: "💼",
  Freelance: "💻",
  Investment: "📈",
  "Food & Dining": "🍔",
  Transport: "🚗",
  Shopping: "🛍️",
  Entertainment: "🎬",
  Health: "💊",
  Education: "📚",
  Utilities: "🔌",
};

// colors for charts
const catColors = {
  "Food & Dining": "#f97316",
  Transport: "#06b6d4",
  Shopping: "#a855f7",
  Entertainment: "#ec4899",
  Health: "#10b981",
  Education: "#3b82f6",
  Utilities: "#f59e0b",
  Salary: "#22c55e",
  Freelance: "#14b8a6",
  Investment: "#6366f1",
};

// aliases so chart rendering code can use the longer names
const CATEGORY_ICONS = catIcons;
const CATEGORY_COLORS = catColors;

const mockData = [
  // january
  {
    id: 1,
    date: "2026-01-01",
    description: "January Salary",
    amount: 75000,
    category: "Salary",
    type: "income",
  },
  {
    id: 2,
    date: "2026-01-03",
    description: "Swiggy - dinner",
    amount: 672,
    category: "Food & Dining",
    type: "expense",
  },
  {
    id: 3,
    date: "2026-01-04",
    description: "Ola cab to office",
    amount: 186,
    category: "Transport",
    type: "expense",
  },
  {
    id: 4,
    date: "2026-01-06",
    description: "Zomato - biryani",
    amount: 487,
    category: "Food & Dining",
    type: "expense",
  },
  {
    id: 5,
    date: "2026-01-07",
    description: "Flipkart - earphones",
    amount: 2499,
    category: "Shopping",
    type: "expense",
  },
  {
    id: 6,
    date: "2026-01-10",
    description: "Netflix",
    amount: 649,
    category: "Entertainment",
    type: "expense",
  },
  {
    id: 7,
    date: "2026-01-12",
    description: "Freelance - logo design",
    amount: 7500,
    category: "Freelance",
    type: "income",
  },
  {
    id: 8,
    date: "2026-01-13",
    description: "Electricity bill",
    amount: 1847,
    category: "Utilities",
    type: "expense",
  },
  {
    id: 9,
    date: "2026-01-16",
    description: "Apollo pharmacy",
    amount: 1134,
    category: "Health",
    type: "expense",
  },
  {
    id: 10,
    date: "2026-01-18",
    description: "Udemy course",
    amount: 499,
    category: "Education",
    type: "expense",
  },
  {
    id: 11,
    date: "2026-01-19",
    description: "Swiggy - lunch",
    amount: 318,
    category: "Food & Dining",
    type: "expense",
  },
  {
    id: 12,
    date: "2026-01-21",
    description: "Amazon - groceries",
    amount: 3164,
    category: "Shopping",
    type: "expense",
  },
  {
    id: 13,
    date: "2026-01-24",
    description: "Freelance - website",
    amount: 12000,
    category: "Freelance",
    type: "income",
  },
  {
    id: 14,
    date: "2026-01-26",
    description: "Petrol",
    amount: 1900,
    category: "Transport",
    type: "expense",
  },
  {
    id: 15,
    date: "2026-01-29",
    description: "PVR movies",
    amount: 820,
    category: "Entertainment",
    type: "expense",
  },
  {
    id: 16,
    date: "2026-01-31",
    description: "Mutual fund SIP",
    amount: 5000,
    category: "Investment",
    type: "expense",
  },

  // february
  {
    id: 17,
    date: "2026-02-01",
    description: "February Salary",
    amount: 75000,
    category: "Salary",
    type: "income",
  },
  {
    id: 18,
    date: "2026-02-01",
    description: "Swiggy - breakfast",
    amount: 224,
    category: "Food & Dining",
    type: "expense",
  },
  {
    id: 19,
    date: "2026-02-04",
    description: "Metro card recharge",
    amount: 500,
    category: "Transport",
    type: "expense",
  },
  {
    id: 20,
    date: "2026-02-07",
    description: "Myntra - clothes",
    amount: 3840,
    category: "Shopping",
    type: "expense",
  },
  {
    id: 21,
    date: "2026-02-10",
    description: "Spotify",
    amount: 119,
    category: "Entertainment",
    type: "expense",
  },
  {
    id: 22,
    date: "2026-02-12",
    description: "Freelance - UI design",
    amount: 15000,
    category: "Freelance",
    type: "income",
  },
  {
    id: 23,
    date: "2026-02-13",
    description: "Zomato - valentine eve",
    amount: 2640,
    category: "Food & Dining",
    type: "expense",
  },
  {
    id: 24,
    date: "2026-02-14",
    description: "Restaurant - dinner out",
    amount: 3100,
    category: "Food & Dining",
    type: "expense",
  },
  {
    id: 25,
    date: "2026-02-16",
    description: "Internet bill",
    amount: 999,
    category: "Utilities",
    type: "expense",
  },
  {
    id: 26,
    date: "2026-02-18",
    description: "Gym membership",
    amount: 2000,
    category: "Health",
    type: "expense",
  },
  {
    id: 27,
    date: "2026-02-21",
    description: "Amazon - laptop stand",
    amount: 1299,
    category: "Shopping",
    type: "expense",
  },
  {
    id: 28,
    date: "2026-02-22",
    description: "Coursera certificate",
    amount: 3500,
    category: "Education",
    type: "expense",
  },
  {
    id: 29,
    date: "2026-02-24",
    description: "Ola - airport drop",
    amount: 782,
    category: "Transport",
    type: "expense",
  },
  {
    id: 30,
    date: "2026-02-28",
    description: "Mutual fund SIP",
    amount: 5000,
    category: "Investment",
    type: "expense",
  },

  // march
  {
    id: 31,
    date: "2026-03-01",
    description: "March Salary",
    amount: 75000,
    category: "Salary",
    type: "income",
  },
  {
    id: 32,
    date: "2026-03-02",
    description: "Swiggy - weekend lunch",
    amount: 543,
    category: "Food & Dining",
    type: "expense",
  },
  {
    id: 33,
    date: "2026-03-03",
    description: "Rapido",
    amount: 94,
    category: "Transport",
    type: "expense",
  },
  {
    id: 34,
    date: "2026-03-05",
    description: "Swiggy - dinner again",
    amount: 412,
    category: "Food & Dining",
    type: "expense",
  },
  {
    id: 35,
    date: "2026-03-07",
    description: "Freelance - app project",
    amount: 20000,
    category: "Freelance",
    type: "income",
  },
  {
    id: 36,
    date: "2026-03-09",
    description: "Amazon Prime",
    amount: 299,
    category: "Entertainment",
    type: "expense",
  },
  {
    id: 37,
    date: "2026-03-11",
    description: "Electricity bill",
    amount: 2063,
    category: "Utilities",
    type: "expense",
  },
  {
    id: 38,
    date: "2026-03-13",
    description: "Doctor visit",
    amount: 500,
    category: "Health",
    type: "expense",
  },
  {
    id: 39,
    date: "2026-03-16",
    description: "Meesho - home stuff",
    amount: 1780,
    category: "Shopping",
    type: "expense",
  },
  {
    id: 40,
    date: "2026-03-20",
    description: "Investment return",
    amount: 4500,
    category: "Investment",
    type: "income",
  },
  {
    id: 41,
    date: "2026-03-21",
    description: "CCD - coffee",
    amount: 340,
    category: "Food & Dining",
    type: "expense",
  },
  {
    id: 42,
    date: "2026-03-24",
    description: "Petrol",
    amount: 2150,
    category: "Transport",
    type: "expense",
  },
  {
    id: 43,
    date: "2026-03-27",
    description: "BookMyShow - concert",
    amount: 1500,
    category: "Entertainment",
    type: "expense",
  },
  {
    id: 44,
    date: "2026-03-30",
    description: "Mutual fund SIP",
    amount: 5000,
    category: "Investment",
    type: "expense",
  },

  // april (so far)
  {
    id: 45,
    date: "2026-04-01",
    description: "April Salary",
    amount: 75000,
    category: "Salary",
    type: "income",
  },
  {
    id: 46,
    date: "2026-04-02",
    description: "Swiggy instamart",
    amount: 1487,
    category: "Food & Dining",
    type: "expense",
  },
  {
    id: 47,
    date: "2026-04-03",
    description: "Uber cab",
    amount: 234,
    category: "Transport",
    type: "expense",
  },
];

const DEFAULT_TRANSACTIONS = mockData;
